### PR TITLE
Add support for digital bits and bytes in SI and IEC units

### PR DESCRIPTION
**Pull request by ericpruitt**

### CODE REVIEW

**Comment by ericpruitt** [comment]
I removed the explicit SI units from this commit since the tool has baked in support for them, but it requires proper capitalization which is generally less of an issue for digital units since powers less than 1 are rarely used. I will restore that commit if you'd be okay with supporting case insensitive prefixes for these units.

**Comment by kevinboone** [comment]
This is a useful and interesting addition to the utility, which I confess I never would have thought of myself. Now I wonder why I didn't ;) However, a couple of things nag at me a little.

First, although the IEC capacity units have well-established meanings, is the same true for kilobyte, megabyte, etc? In uconv, 1Mb = 10^6 bytes because that's what 'mega' means. But in the IT industry I've heard of 1Mb being 10^6, 1024*10^3, and 1024^2 (same as 1 Mib). Is 1Mb = 10^6 now completely universal?

Second, currently you have 'mb' being 'millibyte' which, as you say, is what the SI pefix ought to mean. I think I would prefer for mb to be the same as Mb, but I worry that this is a departure from the way 'm' is used for all other units. In my 30+ years in the computing industry, I've never used or seen the unit 'millibyte' and, of course, 'mb' for 'megabyte' is completely commonplace. Still, I find the loss of consistency a slightly nagging worry. Probably this departure from usual SI practice could be documented somewhere -- but the documentation is pretty scant in general.

I'm happy to merge your changes, in either form, but your comments are welcome, all the same. Feel free to amend what little documentation you can find ;)

**Comment by ericpruitt** [comment]
> First, although the IEC capacity units have well-established meanings, is the same true for kilobyte, megabyte, etc? In uconv, 1Mb = 10^6 bytes because that's what 'mega' means. But in the IT industry I've heard of 1Mb being 10^6, 1024*10^3, and 1024^2 (same as 1 Mib). Is 1Mb = 10^6 now completely universal?

It's a mess. I personally prefer using powers of two and suspect most tech people do, but I've heard some hardware manufacturers and ISPs like SI units because it leads to bigger numbers, and pedants pushing for SI, because pedantry. Conventions when it comes to CLI tools vary. I think most GNU stuff has "--si" and "--human-readable" (or something similar) to differentiate between them when displaying things. However, the approach they use for inputs varies. Inputs are handled as follows (taken from _df(1)_ and _ls(1)_):

> The SIZE argument is an integer and optional unit (example: 10K is 10*1024).  Units are K,M,G,T,P,E,Z,Y (powers of 1024) or KB,MB,... (powers of 1000).  Binary prefixes can be used, too: KiB=K, MiB=M, and so on.

That said, I do think there's value in supporting both: it's useful translating to values that are powers of two so I have a more intuitive sense of what I'm looking at. For example, if I saw disk listed as 30GB, I might run `uconv 30 gb gib` just to see the "real" amount of space. My plan was to add an option to my personal copy of uconv to allow the user to specify whether to assume IEC or SI when using the prefixes; and automatically detect when both IEC units and SI units are being used, so `uconv 2 mb kb` would report "2 mebibytes = 2048 kibibytes" while `uconv 2 mb kib` would convert from SI to IEC. Those changes would be pretty invasive, so I hadn't planned on submitting a pull request for that since I wasn't sure if you would accept the added complexity.

**Comment by kevinboone** [comment]
You've done more work on this in the last ten years than I have so, as far as I'm concerned, this is your project now :)

**Pull request merged**
